name: Update GitHub Actions versions

on:
  schedule:
    - cron: "51 4 * * *"
  workflow_dispatch:

concurrency:
  group: update
  cancel-in-progress: true

permissions: {}

jobs:
  update-versions:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write # needed to commit
      issues: write # needed to create regression issues

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"

      - name: Run tests
        run: python -m unittest test_fetch_versions -v

      - name: Run fetch_versions.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python fetch_versions.py

      - name: Commit changes
        env:
          LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.txt index.json README.md
          git diff --staged --quiet || git commit -m 'chore: update versions' -m "Link: $LINK"
          git push
